"""baseline schema

Revision ID: 6f17c7062a65
Revises: 
Create Date: 2026-07-02 13:48:19.956985+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '6f17c7062a65'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_benchmarks',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('distribution', sa.JSON(), nullable=False),
    sa.Column('citation', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_benchmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_benchmarks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_benchmarks_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_benchmarks_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_benchmarks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_benchmarks_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_benchmarks_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_benchmarks_updated_at'), ['updated_at'], unique=False)

    op.create_table('knowledge_controls',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('framework', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_controls_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_controls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_controls_framework'), ['framework'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_controls_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_controls_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_controls_updated_at'), ['updated_at'], unique=False)

    op.create_table('knowledge_threats',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_threats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_threats_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_threats_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_threats_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_threats_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_threats_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_threats_updated_at'), ['updated_at'], unique=False)

    op.create_table('portfolios',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('scenario_public_ids', sa.JSON(), nullable=False),
    sa.Column('risk_appetite', sa.Float(), nullable=True),
    sa.Column('insurance_offset', sa.JSON(), nullable=True),
    sa.Column('correlation_assumption', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_portfolios_updated_at'), ['updated_at'], unique=False)

    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'APPROVER', 'REVIEWER', 'READONLY', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    op.create_table('app_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('ula_acknowledged_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('ula_acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('ula_acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ula_acknowledged_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_settings_updated_at'), ['updated_at'], unique=False)

    op.create_table('audit_log',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'SIMULATE', 'SNAPSHOT', 'APPROVE', 'SUBMIT_FOR_REVIEW', 'REJECT', 'ARCHIVE', 'EXPORT', 'IMPORT', name='auditaction'), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_updated_at'), ['updated_at'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('captured_by_user_id', sa.Integer(), nullable=True),
    sa.Column('total_ale', sa.Float(), nullable=False),
    sa.Column('total_p50', sa.Float(), nullable=False),
    sa.Column('total_p90', sa.Float(), nullable=False),
    sa.Column('total_p95', sa.Float(), nullable=False),
    sa.Column('total_p99', sa.Float(), nullable=False),
    sa.Column('scenario_count', sa.Integer(), nullable=False),
    sa.Column('simulated_count', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['captured_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_updated_at'), ['updated_at'], unique=False)

    op.create_table('review_schedules',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('cadence_days', sa.Integer(), nullable=False),
    sa.Column('next_due', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['last_reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_schedules_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_schedules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_schedules_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_schedules_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_schedules_next_due'), ['next_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_schedules_updated_at'), ['updated_at'], unique=False)

    op.create_table('scenarios',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('business_unit', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('scenario_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('benchmark_group', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_label', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('mode', sa.Enum('LEF', 'TEF_VULN', 'FULL', name='decompositionmode'), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=False),
    sa.Column('reduction_pct', sa.Float(), nullable=False),
    sa.Column('reference_lines', sa.JSON(), nullable=False),
    sa.Column('prefs', sa.JSON(), nullable=False),
    sa.Column('version_label', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('assessment_date', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=True),
    sa.Column('review_date', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=True),
    sa.Column('approval_state', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ARCHIVED', name='approvalstate'), nullable=False),
    sa.Column('threat_refs', sa.JSON(), nullable=False),
    sa.Column('control_refs', sa.JSON(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=8000), nullable=True),
    sa.Column('deleted_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_approval_state'), ['approval_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_business_unit'), ['business_unit'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_scenarios_scenario_type'), ['scenario_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_updated_at'), ['updated_at'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('scenario_versions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_versions_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_versions_updated_at'), ['updated_at'], unique=False)

    op.create_table('approval_requests',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('scenario_version_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ARCHIVED', name='approvalstate'), nullable=False),
    sa.Column('request_note', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_assigned_reviewer_user_id'), ['assigned_reviewer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_approval_requests_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_scenario_version_id'), ['scenario_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_updated_at'), ['updated_at'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('scenario_version_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='simulationstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('p5', sa.Float(), nullable=True),
    sa.Column('p25', sa.Float(), nullable=True),
    sa.Column('p50', sa.Float(), nullable=True),
    sa.Column('p75', sa.Float(), nullable=True),
    sa.Column('p90', sa.Float(), nullable=True),
    sa.Column('p95', sa.Float(), nullable=True),
    sa.Column('p99', sa.Float(), nullable=True),
    sa.Column('ci_lo', sa.Float(), nullable=True),
    sa.Column('ci_hi', sa.Float(), nullable=True),
    sa.Column('tail_mean', sa.Float(), nullable=True),
    sa.Column('zero_count', sa.Integer(), nullable=True),
    sa.Column('prob_exceed_tolerance', sa.Float(), nullable=True),
    sa.Column('tolerance_at_run', sa.Float(), nullable=True),
    sa.Column('inputs_at_run', sa.JSON(), nullable=False),
    sa.Column('mode_at_run', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('engine_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('sensitivity', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_runs_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_simulation_runs_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_runs_scenario_version_id'), ['scenario_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_runs_updated_at'), ['updated_at'], unique=False)

    op.create_table('simulation_artifacts',
    sa.Column('simulation_run_id', sa.Integer(), nullable=False),
    sa.Column('losses', sa.JSON(), nullable=False),
    sa.Column('sorted_losses', sa.JSON(), nullable=False),
    sa.Column('lefs', sa.JSON(), nullable=False),
    sa.Column('histogram', sa.JSON(), nullable=False),
    sa.Column('lec_curve', sa.JSON(), nullable=False),
    sa.Column('driver_samples', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('simulation_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_artifacts')
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_simulation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_simulation_runs_scenario_version_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_runs_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_runs_public_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_simulation_runs_completed_at'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_updated_at'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_state'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_scenario_version_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_public_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_entity_type'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_entity_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_assigned_reviewer_user_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('scenario_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_versions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_scenario_versions_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_scenario_versions_created_at'))

    op.drop_table('scenario_versions')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_updated_at'))
        batch_op.drop_index(batch_op.f('ix_scenarios_scenario_type'))
        batch_op.drop_index(batch_op.f('ix_scenarios_public_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_name'))
        batch_op.drop_index(batch_op.f('ix_scenarios_mode'))
        batch_op.drop_index(batch_op.f('ix_scenarios_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_scenarios_created_at'))
        batch_op.drop_index(batch_op.f('ix_scenarios_business_unit'))
        batch_op.drop_index(batch_op.f('ix_scenarios_approval_state'))

    op.drop_table('scenarios')
    with op.batch_alter_table('review_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_schedules_updated_at'))
        batch_op.drop_index(batch_op.f('ix_review_schedules_next_due'))
        batch_op.drop_index(batch_op.f('ix_review_schedules_entity_type'))
        batch_op.drop_index(batch_op.f('ix_review_schedules_entity_id'))
        batch_op.drop_index(batch_op.f('ix_review_schedules_created_at'))
        batch_op.drop_index(batch_op.f('ix_review_schedules_active'))

    op.drop_table('review_schedules')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_updated_at'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_created_at'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_updated_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_app_settings_created_at'))

    op.drop_table('app_settings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_updated_at'))
        batch_op.drop_index(batch_op.f('ix_portfolios_public_id'))
        batch_op.drop_index(batch_op.f('ix_portfolios_name'))
        batch_op.drop_index(batch_op.f('ix_portfolios_is_default'))
        batch_op.drop_index(batch_op.f('ix_portfolios_created_at'))

    op.drop_table('portfolios')
    with op.batch_alter_table('knowledge_threats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_threats_updated_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_threats_source'))
        batch_op.drop_index(batch_op.f('ix_knowledge_threats_public_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_threats_name'))
        batch_op.drop_index(batch_op.f('ix_knowledge_threats_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_threats_category'))

    op.drop_table('knowledge_threats')
    with op.batch_alter_table('knowledge_controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_controls_updated_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_controls_source'))
        batch_op.drop_index(batch_op.f('ix_knowledge_controls_public_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_controls_framework'))
        batch_op.drop_index(batch_op.f('ix_knowledge_controls_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_controls_code'))

    op.drop_table('knowledge_controls')
    with op.batch_alter_table('knowledge_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_benchmarks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_benchmarks_source'))
        batch_op.drop_index(batch_op.f('ix_knowledge_benchmarks_public_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_benchmarks_name'))
        batch_op.drop_index(batch_op.f('ix_knowledge_benchmarks_metric'))
        batch_op.drop_index(batch_op.f('ix_knowledge_benchmarks_industry'))
        batch_op.drop_index(batch_op.f('ix_knowledge_benchmarks_created_at'))

    op.drop_table('knowledge_benchmarks')
    # ### end Alembic commands ###
